const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openOverlay: () => ipcRenderer.invoke('overlay:open'),
  toggleOverlay: () => ipcRenderer.invoke('overlay:toggle'),
  closeOverlay: () => ipcRenderer.invoke('overlay:close'),
  chooseDeveloperProject: () => ipcRenderer.invoke('developer:choose-project'),
  clearDeveloperProject: () => ipcRenderer.invoke('developer:clear-project'),
  listDeveloperDirectory: (relativePath) => ipcRenderer.invoke('developer:list-directory', relativePath),
  readDeveloperFile: (relativePath) => ipcRenderer.invoke('developer:read-file', relativePath),
  searchDeveloperCode: (query) => ipcRenderer.invoke('developer:search-code', query),
  buildDeveloperIndex: () => ipcRenderer.invoke('developer:index'),
  searchDeveloperSymbols: (query) => ipcRenderer.invoke('developer:symbol-search', query),
  getDeveloperRepositoryMap: () => ipcRenderer.invoke('developer:repository-map'),
  findDeveloperReferences: (query) => ipcRenderer.invoke('developer:find-references', query),
  assembleDeveloperContext: (payload) => ipcRenderer.invoke('developer:context', {
    query: String(payload?.query || '').slice(0, 200),
    maxTokens: Math.max(64, Math.min(Number(payload?.maxTokens) || 4000, 12000)),
  }),
  runDeveloperVerification: (script) => ipcRenderer.invoke('developer:run-verification', script),
  inspectDeveloperGit: (kind) => ipcRenderer.invoke('developer:git-inspect', kind),
  createDeveloperProposal: (raw, snapshots, verificationScript = null) => ipcRenderer.invoke('developer:proposal-create', { raw, snapshots, verificationScript }),
  approveDeveloperProposal: (id) => ipcRenderer.invoke('developer:proposal-approve', id),
  applyDeveloperProposal: (id) => ipcRenderer.invoke('developer:proposal-apply', id),
  undoDeveloperProposal: (id) => ipcRenderer.invoke('developer:proposal-undo', id),
  getDeveloperProposal: (id) => ipcRenderer.invoke('developer:proposal-get', id),
  getDeveloperSession: () => ipcRenderer.invoke('developer:session'),
  resumeDeveloperSession: (sessionId) => ipcRenderer.invoke('developer:session-resume', sessionId),
  cancelDeveloperTask: () => ipcRenderer.invoke('developer:proposal-cancel'),
  getGeneralSession: () => ipcRenderer.invoke('general:session'),
  createGeneralTask: (input) => ipcRenderer.invoke('general:task-create', input),
  getGeneralTask: (taskId) => ipcRenderer.invoke('general:task-get', taskId),
  startGeneralTask: (taskId) => ipcRenderer.invoke('general:task-start', taskId),
  createGeneralBrowserSession: (taskId) => ipcRenderer.invoke('general:browser-session-create', taskId),
  generalBrowserOperation: (taskId, operation, target) => ipcRenderer.invoke('general:browser-operation', taskId, operation, target),
  planGeneralExecutionAction: (taskId, input) => ipcRenderer.invoke('general:execution-plan', taskId, input),
  getGeneralExecutionAction: (taskId, actionId) => ipcRenderer.invoke('general:execution-get', taskId, actionId),
  validateGeneralExecutionAction: (taskId, actionId) => ipcRenderer.invoke('general:execution-validate', taskId, actionId),
  requestGeneralExecutionConfirmation: (taskId, actionId) => ipcRenderer.invoke('general:execution-confirmation', taskId, actionId),
  confirmGeneralExecutionAction: (taskId, actionId, confirmationId) => ipcRenderer.invoke('general:execution-confirm', taskId, actionId, confirmationId),
  executeGeneralExecutionAction: (taskId, actionId) => ipcRenderer.invoke('general:execution-execute', taskId, actionId),
  observeGeneralExecutionAction: (taskId, actionId) => ipcRenderer.invoke('general:execution-observe', taskId, actionId),
  verifyGeneralExecutionAction: (taskId, actionId, evidence) => ipcRenderer.invoke('general:execution-verify', taskId, actionId, evidence),
  recoverGeneralExecutionAction: (taskId, actionId, options) => ipcRenderer.invoke('general:execution-recover', taskId, actionId, options),
  cancelGeneralExecutionAction: (taskId, actionId, reason) => ipcRenderer.invoke('general:execution-cancel', taskId, actionId, reason),
  replanGeneralTask: (taskId, input) => ipcRenderer.invoke('general:task-replan', taskId, input),
  prepareGeneralDeveloperHandoff: (taskId) => ipcRenderer.invoke('general:task-handoff-developer', taskId),
  getGeneralCapabilities: () => ipcRenderer.invoke('general:capabilities'),
  stopGeneralTask: (taskId) => ipcRenderer.invoke('general:task-stop', taskId),
  pauseGeneralTask: (taskId) => ipcRenderer.invoke('general:task-pause', taskId),
  resumeGeneralTask: (taskId) => ipcRenderer.invoke('general:task-resume', taskId),
  recoverGeneralTask: (taskId) => ipcRenderer.invoke('general:task-recover', taskId),
  observeGeneralTask: (taskId, observation) => ipcRenderer.invoke('general:observe', taskId, observation),
  recordGeneralModelResponse: (taskId, input) => ipcRenderer.invoke('general:model-response', taskId, input),
  prepareGeneralAction: (taskId, name, args) => ipcRenderer.invoke('general:prepare-action', taskId, name, args),
  beginGeneralAction: (taskId) => ipcRenderer.invoke('general:begin-action', taskId),
  confirmGeneralAction: (taskId, confirmationId) => ipcRenderer.invoke('general:confirm-action', taskId, confirmationId),
  completeGeneralAction: (taskId, result) => ipcRenderer.invoke('general:complete-action', taskId, result),
  verifyGeneralAction: (taskId, evidence) => ipcRenderer.invoke('general:verify-action', taskId, evidence),
  markGeneralLoginRequired: (taskId, reason) => ipcRenderer.invoke('general:login-required', taskId, reason),
  setGeneralLoginStatus: (taskId, status) => ipcRenderer.invoke('general:login-status', taskId, status),
  completeGeneralTask: (taskId, status, evidence) => ipcRenderer.invoke('general:task-complete', taskId, status, evidence),
});
