const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openOverlay: () => ipcRenderer.invoke('overlay:open'),
  toggleOverlay: () => ipcRenderer.invoke('overlay:toggle'),
  closeOverlay: () => ipcRenderer.invoke('overlay:close'),
  chooseDeveloperProject: () => ipcRenderer.invoke('developer:choose-project'),
  clearDeveloperProject: () => ipcRenderer.invoke('developer:clear-project'),
  listDeveloperDirectory: (relativePath) => ipcRenderer.invoke('developer:list-directory', relativePath),
  readDeveloperFile: (relativePath) => ipcRenderer.invoke('developer:read-file', relativePath),
  searchDeveloperCode: (query) => ipcRenderer.invoke('developer:search-code', query),
  buildDeveloperIndex: () => ipcRenderer.invoke('developer:index'),
  searchDeveloperSymbols: (query) => ipcRenderer.invoke('developer:symbol-search', query),
  getDeveloperRepositoryMap: () => ipcRenderer.invoke('developer:repository-map'),
  findDeveloperReferences: (query) => ipcRenderer.invoke('developer:find-references', query),
  assembleDeveloperContext: (payload) => ipcRenderer.invoke('developer:context', {
    query: String(payload?.query || '').slice(0, 200),
    maxTokens: Math.max(64, Math.min(Number(payload?.maxTokens) || 4000, 12000)),
  }),
  runDeveloperVerification: (script) => ipcRenderer.invoke('developer:run-verification', script),
  inspectDeveloperGit: (kind) => ipcRenderer.invoke('developer:git-inspect', kind),
  createDeveloperProposal: (raw, snapshots, verificationScript = null) => ipcRenderer.invoke('developer:proposal-create', { raw, snapshots, verificationScript }),
  approveDeveloperProposal: (id) => ipcRenderer.invoke('developer:proposal-approve', id),
  applyDeveloperProposal: (id) => ipcRenderer.invoke('developer:proposal-apply', id),
  undoDeveloperProposal: (id) => ipcRenderer.invoke('developer:proposal-undo', id),
  getDeveloperProposal: (id) => ipcRenderer.invoke('developer:proposal-get', id),
  getDeveloperSession: () => ipcRenderer.invoke('developer:session'),
  resumeDeveloperSession: (sessionId) => ipcRenderer.invoke('developer:session-resume', sessionId),
  cancelDeveloperTask: () => ipcRenderer.invoke('developer:proposal-cancel'),
});
