export type SttFailureClassification =
  | 'AUDIO_PERMISSION'
  | 'AUDIO_CAPTURE_NO_SIGNAL'
  | 'AUDIO_ENCODING'
  | 'STT_AUTH_ERROR'
  | 'STT_BAD_REQUEST'
  | 'STT_RATE_LIMIT'
  | 'STT_TIMEOUT'
  | 'STT_UNSUPPORTED_AUDIO'
  | 'STT_NETWORK_ERROR'
  | 'STT_RESPONSE_PARSE_ERROR'
  | 'STT_UNKNOWN';
